### PR TITLE
Supported mongo cache.

### PR DESCRIPTION
**Pull request by su-chang**
## I'm submitting a...

```
[ ] Bug Fix
[x] Feature
[ ] Other (Refactoring, Added tests, Documentation, ...)
```

## Checklist

- [ ] Commit Messages follow the [Conventional Commits](https://conventionalcommits.org/) pattern
  - A feature commit message is prefixed "feat:"
  - A bugfix commit message is prefixed "fix:"
- [ ] Tests for the changes have been added

## Description

_please describe the changes that you are making_

_for features, please describe how to use the new feature_

_please include a reference to an existing issue, if applicable_

## Does this PR introduce a breaking change?

```
[ ] Yes
[ ] No
```

### CODE REVIEW

**Comment by huan** [comment]
I'm very curious about the reason that we using MongoDB instead of Redis as a cache layer?

**Comment by windmemory** [comment]
> I'm very curious about the reason that we using MongoDB instead of Redis as a cache layer?

If use mongoDB or MySQL or postgrels, this is not cache anymore. For some specific scenario, this makes more sense than a cache layer. For example, we created a web chat page for users to chat, we want to make sure the data that shows on the page are all updated, so we need to sync all the data from wechaty to our DB, this is a lot of conversion and DB read write. So if `wechaty` is able to write to our DB directly, a lot of codes will be saved and also cpu resources. This is why we are trying to explore using mongoDB etc to be the data store for padplus.

**Comment by su-chang** [comment]
We have a new package for this mission, see : https://github.com/juzibot/wechaty-puppet-cache

**Comment by huan** [comment]
Congratulations!

And one suggestion: I believe that the Redis will have 10-100+X faster performance than MongoDB, which is more suitable for this problem.

**Comment by windmemory** [comment]
@huan  I think the name is misleading, this package is actually playing a role of storage instead of cache. With this storage, I believe web interface would be much easier to build, since the server will be able to access `contact`, `room` and `message` data directly from database instead of calling apis on `Wechaty`.

**Comment by huan** [comment]
@windmemory Understood. I hope it can help our to make the web interface easy to be developed!

**Pull request closed without merging**
